### ISSUE TITLE
Nested object as a field

### ISSUE THREAD

**Issue by silentlight** [revolver-app/vuex-orm#15]
Hello,

Is it possible to have nested structure like below?
```
export default class App extends Model {
  static entity = 'apps';

  static fields() {
    return {
      id: this.attr(null),
      ...
      settings: {
        billing_categories: this.hasMany(Category, 'app_id'),
        ...
      },
    };
  }
}
```

It seems that for such a case normalization does not work. 
As a side not, I was able to make it work with normlizr.
Is there any way to make it work?

Thanks!

**Comment by kiaking** [comment]
Interesting. I never thought of this usage.

> It seems that for such a case normalization does not work.

Thank you for trying out! It does not work because currently, Vuex ORM does not iterate nested object, only the top level. 

Actual code where Vuex ORM creates Normalizr schema can be [found here](https://github.com/revolver-app/vuex-orm/blob/master/src/Schema.ts#L39).

For now, there is no way to workaround this issue (I think), but it is possible to add such feature (all we need to do is iterate nested object recursively).

I would like to add this feature. Do you have the code when you made this work with normalizr? I'm not 100% sure how I should define normalizr schema :p

**Comment by silentlight** [comment]
@kiaking using normalizr you can do it like this:
```
const app = new schema.Entity('apps', { 
  ...
  settings: {
    billing_categories: [category]
  }
});

**Comment by kiaking** [comment]
Thanks! Much easier than I thought. I'll work on it.

**Comment by kiaking** [comment]
Now nested object schema is supported with version 0.11.2!
https://github.com/revolver-app/vuex-orm/releases/tag/v0.11.2

@silentlight Thank you for bringing up this idea : )

**Comment by silentlight** [comment]
Awesome. Thanks @kiaking!

**Comment by Tronix117** [comment]
Typings do not seem ok though

**Comment by kiaking** [comment]
@Tronix117 Hi! Sorry we're dropping this feature as stated in #138 . And it's my fault but the dropping is already happening ;(
