### ISSUE TITLE
a demo

### ISSUE THREAD

**Issue by sldobri** [revolver-app/vuex-orm#16]
make a demo

**Comment by kiaking** [comment]
Yeah I should. I'm planning to make one 🚀

**Comment by mastermunj** [comment]
I've started liking the ORM, although a demo covering various aspects of ORM will definitely help a lot for beginners like me.

**Comment by kiaking** [comment]
Thank you for liking ORM! I really do think we need example or demo. I'm working on so stay tuned!

**Comment by zagreusinoz** [comment]
Is it something we can help with?  Did you get started?   I'd love for this to become popular, it deserves it.

**Comment by kiaking** [comment]
I haven't started this yet. It would be really nice if someone could create simple project that shows the benefit of using Vuex ORM. I was thinking some application that shows Blog post with many comments and user editing feature. So that if you change user info, it will update all related comment author or something like that.

if someone has a better idea of what example application should look like, that would be very helpful too.

**Comment by kiaking** [comment]
I've created the example application [at here](https://github.com/revolver-app/vuex-orm-examples). Please let me know if you have even more awesome idea of a demo by creating issue at the example repo 🎸
