### ISSUE TITLE
Feature Request: Query Addons

### ISSUE THREAD

**Issue by afixia** [revolver-app/vuex-orm#37]
I've implemented a hacky solution to implement fuse.js (fuzzy object search library) to filter api data based on user input before calling your create method.

It would be convenient to extend the Query class to provide my own fuse.js interface for regex matching.

I understand I can use the source code to extend your classes, but I think it would a great feature to allow add-ons in the install constructor.

Obviously we don't want to bloat core library with unnecessary packages, so allowing optional add-ons would be the solution.

I'd be happy to maintain the first add-on for fuzzy search but I would defer to your implementation of how to handle add-on interfaces.

**Comment by kiaking** [comment]
This is a very interesting idea, and I would love to work on to this. I want to discuss how to implement this feature.

To extend Query or Repo class, the simplest way I came up is something like below.

```js
// Import addon.
import { installFuse } from 'vuex-orm-fuse'

// Add addons by passing function to the addons option.
const store = new Vuex.Store({
  plugins: [VuexORMInstall(database, {
    addons: [installFuse] // `installFuse` should be a function.
  })]
})

// installFuse implementation. Vuex ORM will pass Repo and Query class
// as a callback argument.
export default function (repo, query) {
  // To extend query class, simply you may add prototype methods.
  query.prototype.search = function () {
    // Custom search method implementation.
  }

  // Or maybe it is better to have something like extend method?
  query.extend({
    search () {
      // Search method implementation.
    }
  })
}
```

It will treat Repo and Query as a singleton. What do you think?

If you have any preferred way to tackle this issue, I would love to hear that.

**Comment by afixia** [comment]
I like the idea of using query.extend() as to inherit class methods. One of the parameters of fuse is an array of column names (object properties) and in order to keep it dynamic I would like to have access to the model api to set all fields (minus primaryKey).

I will play with this idea today and let you know. Thanks for the feedback!

**Comment by cjcrawford** [comment]
I'm a little green on typescript, so I'm hoping to trigger some ideas...

Can you use namespacing / modules to allow [Declaration Merging](https://www.typescriptlang.org/docs/handbook/declaration-merging.html) ?

Here's some example code for an add-on that felt pretty simple

**Plugin Install**

```typescript
// vuex-orm-search-plugin/index.ts

import {Repo, Query} from './plugin'

export const install = function (query: any, repo: any) {
  query.extents(Query)
  repo.extends(Repo)
}

export default install
```

**Main Plugin Code**

```typescript
// vuex-orm-search-plugin/plugin.ts

import * as Fuse from 'fuse.js'
import {Records} from 'vuex-orm/lib/Data'

export interface SearchQuery {
  term: string,
    columns: Array<any>
}

export interface QueryInterface {
  addSearch(term: string, columns: Array<any>): this
  search(records: Records): Records
  _process(records: Records): Records
}

export interface RepoInterface {
  search(term: string, columns: Array<any>): this
}

export class Query implements QueryInterface {
  protected searches: Array<SearchQuery> = []

  addSearch (term: string, columns: Array<any>): this {
    this.searches.push({term, columns})
    return this
  }

  search (records: Records): Records {
    let searches = this.searches
    for (let query of searches) {
      console.log('filter term: ', query.term)
      console.log('on columns: :', query.columns)
      let fuse = new Fuse(records as any, {
        keys: query.columns
      })
      records = fuse.search(query.term) as any
    }
    return records
  }

  _process (records: Records): Records {
    return this.search(records)
  }
}

export class Repo implements RepoInterface {
  protected query: Query

  constructor (query: Query) {
    this.query = query
  }

  search (term: string, columns: Array<string>): this {
    this.query.addSearch(term, columns)
    return this
  }
}

```

**Comment by kiaking** [comment]
Thanks for the feedback guys. OK I've thinking about this and I wanted to tweak how things work a bit.

First of all, I was checking how Vue plugins works and how Vuex plugin works. There is a difference which Vue plugin lets extend Vue it self (not vue instance) but Vuex plugin lets extends store instance (not Store it self).

And how Vuex ORM plugin should work is it needs to extend VuexORM (Model, Repo, Query and such) it self and not there instances.

So, I think it is better to adhere to Vue plugin implementation instead of Vuex plugin implementation like below. Here I'll take example code from @cjcrawford.

### How user install addons.

```js
import VuexORM from 'vuex-orm'
import Search from 'vuex-orm-search-plugin'

// Plugin specific options if there are any.
const options = {}

// Install plugin.
// The plugin should be a function.
VuexORM.use(Search, options)
```

### Plugin implementation (vuex-orm-search-plugin)

```js
// Plugin will receive two arguments.
// `components` is the object containing Model, Repo and such.
// `options` is the object user passed in.
export default function (components, options = {}) {
  // Add global method to the Model.
  components.Model.globalMethod = function () {
    // something logic ...
  }

  // Add instance method to the Repo.
  components.Repo.prototype.search = function () {
    // something logic ...
  }
}
```

This is pretty much the same as how Vue plugin works.
https://vuejs.org/v2/guide/plugins.html

Vue only pass `Vue` to the plugin but VuexORM have many components so I wrapped them into object. This way you could use object destructuring too.


```js
export default function ({ Model, Repo }, options = {}) {
  // Add global method to the Model.
  Model.globalMethod = function () {
    // something logic ...
  }

  // Add instance method to the Repo.
  Repo.prototype.search = function () {
    // something logic ...
  }
}
```

There are many ways to enable addons to the VuexORM, for example use `extend` method is one way too, but I though we should adhere to the Vue or Vuex implementation because Vuex ORM is also a plugin for the Vue family.

Therefor, I'm trying to avoid class extend pattern here.

I would love to here a feedback on this.


@afixia 

> I would like to have access to the model api to set all fields (minus primaryKey).

You can get access to the model through Repo class.

```js
const repo = store.getters['entitites/users/query']()

const User = repo.model(repo.name) // You get User class.
```

**Comment by cjcrawford** [comment]
Love it. Excited to test it out!

**Comment by kiaking** [comment]
I've created PR #39 to add this feature. It's not fully ready but I would love to hear feedback!

@afixia 
Is it possible for you to start building the addon and create repository? I will be more than happy to look into it and give some help if you need any.

**Comment by cjcrawford** [comment]
Yes I will start the search plugin repository and share after testing.

I think we should create a new requirement / optional documentation on how we can expose add-on processing methods to the Query class that trigger before the limit and sort get applied.

Perhaps in Query class you can add a protected array of callback functions to execute in the process lifecycle that must return records.

This way a plugin can create a unique prototype global method for processing logic then push that callback method to the global process array.

In Query.process you can loop and execute any methods in the array before applying sort and limit.

I'm open to suggestions on how to implement but there needs to be a standard in place for how to hook into your process method before we slice final results.

Thanks for all the work on this! I'm excited to help create many plugins. I have quite a few ideas that exist in my store that I would love to refactor into plugins and share with the community.

**Comment by kiaking** [comment]
Thank you for trying out things!

I like the idea of having `records` array to store entity's data. It's not implemented so I'll do this!

However, I think maybe we might need to add lifecycle hook feature.

It is possible to store all entity records on query construction (and I will), but Vuex ORM has to wait to modify that records until the user execute `get` or `first` method. This means Vuex ORM can't update the records array right after `when` or `orderBy` method is called.

Mainly because of `orWhere` method. Vuex ORM must wait processing data until all of the conditions are added to the Query instance.

That's been said, if the plugin only needs to modify records before `when`, `orderBy`, `limit` and `offset` is processed, there's no problem. The plugin can simply modify the records array. However, I think there is a situation where the plugin would like to work with records that are filtered by `where` but before `orderBy` or `limit`, or even the final result.

To do this, I'm thinking to add the following lifecycle.

1. beforeProcess
2. beforeWhere
3. beforeOrderBy
4. beforeLimit
5. beforeGet

Then the plugin can hook into at any lifecycle by special `on` method.

```js
function install ({ Query }) {
  // Execute callback before Vuex ORM sort the record. The `records` are
  // the filtered data by `where` method.
  Query.on('beforeOrderBy', (records) => {
    // Should return modified records.
    return // Do something with record.
  })
}
```

Obviously, we can add other lifecycle hooks such as `beforeCreate`, `afterUpdate`, etc.

Does this make sense to you? If it's good idea, I'm willing to work on to this :)

**Comment by cjcrawford** [comment]
I started my plugin repo based on the #40. After using my PR and my plugin repo I tested on a large project currently using VuexORM and it works great!

Happy to adjust the plugin to work within your scope, I was just giving you a quick idea of what I wanted to be able to do.

Here's the init plugin: https://github.com/cjcrawford/vuex-orm-plugin-search

**Comment by cjcrawford** [comment]
Love the lifecycle hooks as it provides greater flexibility for future plugins. Let's do it! It's also very Vue like in the approach. Perhaps by exposing events a user could implement their own methods without needing a plugin :)

This particular plugin just needs access to records before limit() but changing to hook into a beforeLimit event would be just as easy to do.

**Comment by kiaking** [comment]
Wow this is awesome! Thank you for the great work! I'll finish up #39 first then release it. After that I'll start creating the lifecycle methods. I'll add issue for that.

**Comment by kiaking** [comment]
@cjcrawford I was refactoring some Query code, and I would like to ask you if it's ok to change `this.records` of Query to be an Array instead of an object. I think it would be easier for vuex-orm-plugin-search too.

Let me know if this is going to a problem!

**Comment by cjcrawford** [comment]
Yes. That works for me. Saves me from having to map the records then having to reduce them back to Object. 

I wanted to keep your structures in tact in my pull request but if you want to change it to an array, go for it.

**Comment by kiaking** [comment]
Now Vuex ORM 0.15.0 is out with plugin support! [See the documentation](https://revolver-app.gitbooks.io/vuex-orm/plugins.html) for the final docs!
